# -*- coding: utf-8 -*-
"""Ezz_Medical_Task.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t0NfLFjkADbThnT8leq64XC_aenoqyrJ

#Setup
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install -Uq "unstructured[all-docs]" pillow lxml pillow
# %pip install -Uq chromadb tiktoken
# %pip install -Uq langchain langchain-community langchain-openai langchain-groq
# %pip install -Uq python_dotenv

!pip install langchain-google-genai
!pip install -U langchain-huggingface
!apt-get install -y poppler-utils

pip install open-clip-torch

"""#Importing Main Libraries"""

from unstructured.partition.pdf import partition_pdf
import numpy as np
from PIL import Image
import torch
from transformers import CLIPProcessor , CLIPModel
from langchain_google_genai import ChatGoogleGenerativeAI
import chromadb
from chromadb.utils.embedding_functions import SentenceTransformerEmbeddingFunction, OpenCLIPEmbeddingFunction
from chromadb.utils.data_loaders import ImageLoader

"""#Split PDF into Chunks"""

def PDF_Splitter(path):
  chunks=partition_pdf(
      filename=path,
      infer_table_structure=True,
      chunking_strategy="by_title",
      max_characters=2000,
      extract_image_block_types=["Image"],
      extraxt_images_in_pdf=True

  )
  return chunks

"""#Separating the extracted data into Text , Images & Tables"""

def Extract_data(chunks):
  Images=[]
  Text=[]
  Tables=[]
  for chunk in chunks:
    if "Table" in str(type(chunk)):
      Tables.append(chunk)
    if "CompositeElement" in str(type(chunk)):
      Text.append(chunk)
      meta_data=chunk.metadata.orig_elements
      for data in meta_data:
        if "Image" in str(type(data)):
          Images.append(data.metadata.image_path)
  return Text , Tables , Images

"""#Store the Embedding vectors into Chroma DB"""

def create_vector_db(Text, Tables, Images):
    client = chromadb.Client()
    text_embedding = SentenceTransformerEmbeddingFunction(model_name="all-MiniLM-L6-v2")
    text_collection = client.get_or_create_collection(
        name="text",
        embedding_function=text_embedding
    )
    data_loader = ImageLoader()

    text_strings = [str(chunk.text) for chunk in Text]
    table_strings = [str(tbl) for tbl in Tables]
    all_texts = text_strings + table_strings

    text_collection.add(
        ids=[f"text_{i}" for i in range(len(all_texts))],
        documents=all_texts
    )

    image_embedding = OpenCLIPEmbeddingFunction()

    image_collection = client.get_or_create_collection(
        name="image",
        embedding_function=image_embedding,
        data_loader=data_loader
    )



    image_collection.add(
        ids=[f"image_{i}" for i in range(len(Images))],
        uris=Images,
        metadatas=[{"file": path} for path in Images]
    )

    return text_collection, image_collection

"""#Preparing Prompt for LLM"""

from IPython.display import Image, display

def asking_question(query, db, images_db, llm):
    text_results = db.query(
        query_texts=[query],
        n_results=3,
        include=["documents"]
    )
    retrieved_texts = text_results.get("documents", [[]])[0]
    context = "\n".join(retrieved_texts) if retrieved_texts else ""

    prompt = f"""
Use the context to answer the user's question.

Context:
{context}

Question: {query}
Answer:"""

    retrieved_images = []
    if images_db is not None:
        img_results = images_db.query(
            query_texts=[query],
            n_results=1,
            include=["metadatas"]
        )
        metas = img_results.get("metadatas", [[]])[0]
        if metas:
            retrieved_images = [m.get("file", "unknown") for m in metas]
            image_info = ", ".join(retrieved_images)
            prompt += f"\n\nRelated images (filenames): {image_info}"
    answer = llm.invoke(prompt).content
    print(answer)
    if retrieved_images:
        print("\n Related images:")
        for img_path in retrieved_images:
            try:

                display(Image(filename=img_path))
            except Exception as e:
                print(f"Could not display {img_path}: {e}")

    return answer

PDF_Path="/content/Optimizing Redundancy Detection in Software Requirement Specifications Using BERT Embeddings.pdf"

chunks=PDF_Splitter(PDF_Path)
text, tables , images= Extract_data(chunks)

db,images_db=create_vector_db(text, tables , images)

import os
import getpass
os.environ["GOOGLE_API_KEY"] = getpass.getpass("Enter your Google Gemini API key: ")

llm = ChatGoogleGenerativeAI(model="gemini-2.5-pro",  google_api_key=os.environ["GOOGLE_API_KEY"])

response = asking_question("Provide a comparative analysis between BERT embeddings and average Word2Vec embeddings", db, images_db, llm)